name: wordle
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  shared_preferences: ^2.0.12
  top_snackbar_flutter: ^1.0.2
  twemoji: ^0.4.2
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/words.txt
    - assets/svg/
