name: wordle
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.13
  top_snackbar_flutter: ^1.0.2
  twemoji: ^0.4.2
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
     - assets
